version: '3.6'

services:

  chatgpt:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    platform: linux/amd64
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY=000000000000000'
      - 'OPENAI_API_HOST=http://api:8000'
      - HTTP_PROXY=http://127.0.0.1:8889
      - HTTPS_PROXY=http://127.0.0.1:8889

  api:
    build: .
    volumes:
      - ./models:/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - 8000:8000
    environment:
      - MODEL=/models/ggml-vicuna-13b-1.1-q4_0.bin
      - DISPLAY=0
      - HTTP_PROXY=http://127.0.0.1:8889
      - HTTPS_PROXY=http://127.0.0.1:8889
